name: PocketVote
main: ProjectInfinity\PocketVote\PocketVote
version: 2.1.4
api: [3.0.0]
author: ProjectInfinity
permissions:
  pocketvote.admin:
    description: ""
    default: op
  pocketvote.vote:
    description: ""
    default: true
